/**
 * Character Engine — Core Types
 *
 * These interfaces define the contract between:
 *   - SVG source files (Inkscape)
 *   - Schema extractor (scripts/extract_schema.ts)
 *   - Renderers (svg.ts, skia.ts)
 *   - Expression system (protocol.ts)
 *
 * Schema versioning: bump schemaVersion when groups/controls change.
 * Write a SchemaAdapter to bridge old → new. Renderers declare which
 * version they support; AdapterRegistry handles the rest.
 */

// ─── Primitives ───────────────────────────────────────────────────────────────

export interface Vec2 {
  x: number;
  y: number;
}

// ─── Control points ───────────────────────────────────────────────────────────
// Declared per animatable group. Drives a single degree of freedom.

export type ControlType =
  | "rotate"       // rotate group around anchor pivot
  | "scaleY"       // scale vertically around anchor center
  | "translateXY"  // shift group by (dx, dy)
  | "bezierY"      // move a bezier control point's Y
  | "color"        // change stroke/fill color
  | "glow";        // change blur radius on a filter

export interface ControlPoint {
  id: string;              // e.g. "angle", "openness", "curveY", "color"
  type: ControlType;
  anchor: Vec2;            // pivot for rotate, center for scale, handle pos for bezierY
  rest: number | string;   // value at neutral pose
  range: {
    min: number;
    max: number;
  };
}

// ─── Layer groups ─────────────────────────────────────────────────────────────
// Mirrors the Inkscape layer/group structure from the SVG.

export interface LayerGroup {
  id: string;              // Inkscape group id e.g. "g28726"
  label: string;           // Inkscape label e.g. "left"
  animatable: boolean;
  controls: ControlPoint[];
}

// ─── Character schema ─────────────────────────────────────────────────────────
// The full rig definition for one character. Generated by the extractor,
// consumed by renderers. Versioned for forward compatibility.

export interface CharacterSchema {
  schemaVersion: string;   // e.g. "1.0"
  characterId: string;     // e.g. "robot"
  svgFile: string;         // relative path to SVG source
  viewBox: string;         // SVG viewBox string
  rootTransform: string;   // parent group transform string

  // Animatable group controls — extracted from SVG geometry
  controls: {
    brows: {
      left:  BrowControls;
      right: BrowControls;
    };
    eyes: {
      left:  EyeControls;
      right: EyeControls;
    };
    mouth: MouthControls;
    signal: SignalControls;
    // Pre-drawn overlay layers keyed by overlay param name
    // e.g. "blush" | "tearDrop" | "sweatDrop" | "heartFloat" | "confused"
    emotions: Record<string, EmotionLayer>;
  };
}

export interface BrowControls {
  pivot: Vec2;
  range: { min: number; max: number };
  restAngle: number;
}

export interface EyeControls {
  anchor: Vec2;
  rx: number;
  ry: number;
  opennessRange: { min: number; max: number };
  lookXRange:    { min: number; max: number };
  lookYRange:    { min: number; max: number };
}

export interface MouthControls {
  x1: number;
  x2: number;
  y: number;
  controlX: number;
  controlY_rest: number;
  controlY_min: number;   // frown
  controlY_max: number;   // smile
}

export interface SignalControls {
  orbCenter: Vec2;
  glowRange: { min: number; max: number };
  colors: {
    idle: string;
    thinking: string;
    alert: string;
    error: string;
  };
}

// ─── Emotion layers ───────────────────────────────────────────────────────────
// Pre-drawn Inkscape groups toggled on/off by the renderer.
// elements[] is used by Skia/RN; id is used by web SVG DOM toggle.

export interface EmotionElement {
  type: "path" | "ellipse" | "rect";
  d?: string;             // path data (path only)
  cx?: number; cy?: number; rx?: number; ry?: number; // ellipse
  x?: number; y?: number; width?: number; height?: number; // rect
  fill?: string;
  fillOpacity?: number;
  fillRule?: string;
  stroke?: string;
  strokeWidth?: number;
  transform?: string;     // element-local transform (on top of rootTransform)
}

export interface EmotionLayer {
  id: string;             // Inkscape layer id — web SVG toggles display on this
  elements: EmotionElement[];
}

// ─── Control values ───────────────────────────────────────────────────────────
// Concrete per-frame values output by the mapping layer.
// These are what renderers consume — no normalization, actual units.

export interface ResolvedControls {
  brows: {
    left:  { angle: number };
    right: { angle: number };
  };
  eyes: {
    left:  { scaleY: number; dx: number; dy: number; color: string };
    right: { scaleY: number; dx: number; dy: number; color: string };
  };
  mouth: {
    shape: "bezier" | "open" | "flat";
    controlY: number;
    openRy: number;        // for O-mouth ellipse
  };
  signal: {
    color: string;
    glowRadius: number;
  };
  overlay: {
    screenTint: string | null;
    blush: boolean;
    tearDrop: boolean;
    sweatDrop: boolean;
    heartFloat: boolean;
  };
}

// ─── Schema versioning ────────────────────────────────────────────────────────

export interface SchemaAdapter {
  fromVersion: string;
  toVersion: string;
  adapt(schema: CharacterSchema): CharacterSchema;
}

export interface AdapterRegistry {
  register(adapter: SchemaAdapter): void;
  adapt(schema: CharacterSchema, targetVersion: string): CharacterSchema;
}

// ─── Renderer registry ────────────────────────────────────────────────────────

export type RendererPlatform = "svg-web" | "skia-rn" | string;

export interface RendererFactory<T> {
  platform: RendererPlatform;
  supportedSchemaVersion: string;
  create(schema: CharacterSchema): T;
}

export interface RendererRegistry<T> {
  register(factory: RendererFactory<T>): void;
  getCompatible(platform: RendererPlatform, schemaVersion: string): RendererFactory<T> | null;
}
